In [1]:
import numpy as np

## how to create an array

### 1d array

In [2]:
array = np.array([6, 2, 7, 8])

In [3]:
array

array([6, 2, 7, 8])

### 2d array

In [4]:
array2 = np.array([[10, 20, 30, 40, 50],[1, 3, 5, 6, 8]])

In [5]:
array2

array([[10, 20, 30, 40, 50],
       [ 1,  3,  5,  6,  8]])

## how check type

In [6]:
type(array)

numpy.ndarray

In [7]:
type(array2)

numpy.ndarray

## how to chek dimension

In [8]:
array.ndim

1

In [9]:
array2.ndim

2

## how to find max element

In [10]:
array.max()

8

In [11]:
# 2d array with axis = none : it is considerd as 1d array
array2.max()

50

In [12]:
# 2d array with axis = 1 : ==> it applied rowwise
array2.max(axis = 1)

array([50,  8])

## how to find min element

In [13]:
array.min()

2

In [14]:
# 2d array with axis = none : it is considerd as 1d array
array2.min()

1

In [15]:
# 2d array with axis = none : it is considerd as 1d array
array2.min(axis = 1)

array([10,  1])

## how to calculate cumullative sum

In [16]:
array.cumsum()

array([ 6,  8, 15, 23], dtype=int32)

In [17]:
# axis = none
array2.cumsum()

array([ 10,  30,  60, 100, 150, 151, 154, 159, 165, 173], dtype=int32)

In [18]:
# axis = 0 : columnwise operation
array2.cumsum(axis = 0)

array([[10, 20, 30, 40, 50],
       [11, 23, 35, 46, 58]], dtype=int32)

In [19]:
# axis = 1 : rowwise operation
array2.cumsum(axis = 1)


array([[ 10,  30,  60, 100, 150],
       [  1,   4,   9,  15,  23]], dtype=int32)

## how to calculate cumullative multiplication

In [20]:
array.cumprod()

array([  6,  12,  84, 672], dtype=int32)

In [21]:
# axis = none ==>it is considerd as 1d array
array2.cumprod()

array([        10,        200,       6000,     240000,   12000000,
         12000000,   36000000,  180000000, 1080000000,   50065408],
      dtype=int32)

In [22]:
# axis = 0 : columnwise operation
array2.cumprod(axis = 0)

array([[ 10,  20,  30,  40,  50],
       [ 10,  60, 150, 240, 400]], dtype=int32)

In [23]:
# axis = 1 : rowwise operation
array2.cumprod(axis = 1)


array([[      10,      200,     6000,   240000, 12000000],
       [       1,        3,       15,       90,      720]], dtype=int32)

## if we want to apply arithmatic operators

In [24]:
array + 10

array([16, 12, 17, 18])

In [25]:
array2 + 10

array([[20, 30, 40, 50, 60],
       [11, 13, 15, 16, 18]])

In [26]:
array - 2

array([4, 0, 5, 6])

In [27]:
array * 5

array([30, 10, 35, 40])

In [28]:
array / 2

array([3. , 1. , 3.5, 4. ])

## how to listout methods of numpy

In [29]:
dir(array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

## how to get info about method of numpy

In [30]:
help(array.argmax)

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



In [31]:
array

array([6, 2, 7, 8])

## argmax() : this method gives indices of maximum values along the given axis

In [32]:
array.argmax()

3

In [33]:
# axis = none
array2.argmax()

4

In [34]:
# axis = 0
array2.argmax(axis = 0)

array([0, 0, 0, 0, 0], dtype=int64)

In [35]:
# axis = 1
array2.argmax(axis = 1)

array([4, 4], dtype=int64)

## argmin() : this method gives indices of minimum values along the given axis

In [36]:
array.argmin()

1

In [37]:
# axis = none
array2.argmin()

5

In [38]:
# axis = 0
array2.argmin(axis = 0)

array([1, 1, 1, 1, 1], dtype=int64)

In [39]:
# axis = 1
array2.argmin(axis = 1)

array([0, 0], dtype=int64)

## if we have array data and we want to convert it into list

**if we have 1d array then we can use list() constructor to convert array data into list**



In [40]:
list(array)

[6, 2, 7, 8]

**but when we have 2d array **

In [41]:
list(array2)

[array([10, 20, 30, 40, 50]), array([1, 3, 5, 6, 8])]

## use of tolist() method

**when we want to convert 2d array data into list we can use tolist() method**

In [42]:
array2.tolist()

[[10, 20, 30, 40, 50], [1, 3, 5, 6, 8]]

# create an array using builtin functions

### using arange() function

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [45]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])