## using list

In [1]:
import numpy as np

In [2]:
l = [1, 2, 4, 5, 6] #this is list
array = np.array(l)

In [3]:
array

array([1, 2, 4, 5, 6])

## or

In [4]:
array = np.array([1, 2, 4, 5, 6])

In [5]:
array

array([1, 2, 4, 5, 6])

## 2d array

In [6]:
array2 = np.array([[10, 20, 30, 40, 50],[1, 3, 5, 6, 8]])

In [7]:
array2

array([[10, 20, 30, 40, 50],
       [ 1,  3,  5,  6,  8]])

## create an array using builtin functions

# arange()

### syntax:- arange([start,] stop[, step,], dtype=None, *, like=None)

### def:- create an 1d array of evenly spaced values with in a given interval. it gives integer values.
### 


### 1d array

In [8]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10) # start = 1, stop = 10 which is exclusive

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10,2) # start = 1, stop = 10 which is exclusive , step = 2

array([1, 3, 5, 7, 9])

In [11]:
np.arange(10, dtype = float) # using dtype = float.

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [12]:
np.arange(10, dtype = complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

# zeros()

### syntax:- zeros(shape, dtype=float, order='C', *, like=None)

### def :- creates an array filled with zeros. using shape paramete we can create 1d or 2d array.shape parameter is required. it gives float values.

In [13]:
np.zeros(10) # 1d array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(10, dtype = int) # 1d array with integre values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# 2d array
np.zeros((4,3), dtype = int) # it gives 4 rows 3 coloumns integer values.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# ones()
### syntax :- np.ones(shape, dtype=None, order='C', *, like=None)
### def :- creates an array filled with ones. using shape paramete we can create 1d or 2d array.shape parameter is required. it gives float values.

In [16]:
np.ones(10) # 1d aray with float values

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((3,3), dtype = int) # 2d array means combination of rows and coloumns(3 rows and 3 coloumns) with integer values

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# linspace()
### syntax :- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
### def :- create an array filled with evenly spaced values. bydefault it gives 50 values and here endpoint is included.

In [18]:
np.linspace(1,10) # it creates an array filled with evenly spaced values.bydefault it gives 50 values. bcz num = 50 bydefault.

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [19]:
np.linspace(1,10 , num = 5)  # num = 5 gives 5 evenly spaced values between 1 to 10.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
# bydefault endpoint is included but when we use endpoint=False, endpoint is exluded.
np.linspace(1,10 , num = 5, endpoint = False) 

array([1. , 2.8, 4.6, 6.4, 8.2])

In [21]:
# if we want to check diffrence or spacing between each number then use retstep=True. bydefault is is false
# diffrence between each number is 0.9
np.linspace(1,10 , num = 10, endpoint = False, retstep=True ) 

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [22]:
# if i want int number then use dtype=int 

np.linspace(1,10 , num = 10, endpoint = False, retstep=True, dtype=int)

(array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 0.9)


# eye()
### syntax :- np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
### def :- creates 2d array filled with zeros except  digonal element.here digonal elements ae equal to 1.


In [23]:
# it will gives 5 rows and 5 coloumns.
# here by default dtype = float and k = 0(index of digonal)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# if 1 want 4 rows and 5 columns 
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [25]:
# i want integer values 
np.eye(4,5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [26]:
# use k=1 
np.eye(4,5, dtype = int, k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# identity()
### syntax :- np.identity(n, dtype=None)
### def :- creates 2d square array filled with zeros except digonal elements.here digonal elements are equal to 1.
### it is same as eye() function.by default it gives float values.

In [27]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.identity(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# full()
### syntax : - np.full(shape, fill_value, dtype=None)
### def :- create a new array of given shape and type, filled with `fill_value`.

In [29]:
# gives 1d array filled with 3
np.full(5, fill_value = 3)

array([3, 3, 3, 3, 3])

In [30]:
# it gives 5 rows and 3 columns 2d array filled with 3
np.full((5,3), fill_value = 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

# random()
### random is a module in numpy. it gives andom values in a given shape.there are many functions in random.
### rand(), randn(), randint(), randchoice(), randseed(), etc


## np.random.random()
### syntax : - np.random.random(size = none)
### def :- create array of specified shape filled with random values as per uniform distribution. values will be in [0,1] interval

In [31]:
# it will gives array of 5 random float values between [0,1] interval.
np.random.random(5)

array([0.5289597 , 0.46635661, 0.4817828 , 0.10155429, 0.30916396])

In [32]:
# shape = (5,3) means it will give 5 rows and 3 coloumns
np.random.random((5,3))

array([[0.89939539, 0.00582572, 0.33052803],
       [0.51109621, 0.34852785, 0.18950402],
       [0.5942253 , 0.17336303, 0.64297998],
       [0.62996272, 0.64662047, 0.33166434],
       [0.17419035, 0.16092074, 0.09864026]])

## np.random.rand()
### syntax : - np.random.rand(size = none)
### def :- create array of specified shape filled with random values as per uniform distribution. values will be in [0,1] interval¶

In [33]:
# it will gives array of 5 random float values between [0,1] interval.
np.random.rand(5)

array([0.62077684, 0.74021594, 0.18403367, 0.3246012 , 0.5066262 ])

In [34]:
# shape = (5,3) means it will give 5 rows and 3 coloumns
np.random.rand(5,3)

array([[0.2278846 , 0.02199282, 0.51301908],
       [0.00429239, 0.86551886, 0.15615449],
       [0.98045954, 0.41792441, 0.39683323],
       [0.48457777, 0.09473141, 0.52803439],
       [0.16419508, 0.81984686, 0.6427646 ]])

In [35]:
np.random.rand(4,2,3)

array([[[0.55299544, 0.1103178 , 0.21918722],
        [0.99915943, 0.18568823, 0.69111684]],

       [[0.22096215, 0.08150009, 0.085112  ],
        [0.41928801, 0.44488536, 0.96241934]],

       [[0.40944904, 0.3167509 , 0.489704  ],
        [0.96529417, 0.60225132, 0.39412057]],

       [[0.21000049, 0.67090631, 0.76422259],
        [0.88183097, 0.37127002, 0.10910493]]])

# randint()
### syntax :- np.random.randint(low, high=None, size=None, dtype=int)
### def :- creates array of specified shape filled with random integers from low (inclusive) to high (exclusive).if high is not mensioned then interval will be [0, low]

In [36]:
# create 1d array (bcz size  = 4) filled with random integers from 0 to 4 (low is 5 and high is not mensioned)
np.random.randint(5, size = 4)

array([2, 3, 0, 2])

In [37]:
# create 1d array (bcz size  = 4) filled with random integers from low = 5 to high = 10 (exclusive)
np.random.randint(5, 10, size = 4)

array([9, 7, 7, 7])

In [38]:
# create 2d array (bcz size  = (4,3)) filled with random integers from low = 5 to high = 10 (exclusive)
np.random.randint(5, 10, size = (4,3))

array([[8, 5, 5],
       [6, 7, 8],
       [8, 6, 9],
       [7, 8, 9]])

# randn()
### syntax : - np.random.rand(shape)
### def :- create array of specified shape filled with random values as per "standard normal" distribution.

In [39]:
np.random.randn(6)

array([-0.79669137,  0.05833213,  0.34214993,  0.35793253,  1.20455513,
       -0.49148493])

In [40]:
np.random.randn(6 ,2)

array([[-0.87615376, -0.11781636],
       [ 1.98284862,  0.98207699],
       [ 1.89702962, -0.9306538 ],
       [-0.63692382,  0.3802688 ],
       [-0.83035719,  1.96510535],
       [-0.58416746,  0.22940375]])

In [41]:
d = np.arange(16).reshape(4,4)

In [42]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
np.diag([True,True,True])

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [50]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [52]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [53]:
np.full((3,3),2) + np.diag([1,2,3])

array([[3, 2, 2],
       [2, 4, 2],
       [2, 2, 5]])