In [1]:
import numpy as np

In [2]:
# create an array
a = np.arange(1,10).reshape(3,3)

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b  =  np.arange(1,10).reshape(3,3)

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
c = np.arange(1,7).reshape(2,3)

In [7]:
c

array([[1, 2, 3],
       [4, 5, 6]])

# add()
### syntax : - add(x1,x2)          here x1,x2 ae the arrays to be added.
### add method is used to add arrays element-wise.when we perfom add() function on array,we make sure that array will be have in the same shape.
### it returns reflection . original array will not change.

In [8]:
np.add(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
np.add(a,10)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# append()
### syntax :- np.append(arr, values, axis=None)
### def : - Append values to the end of an array.original array will not change.

## 1d array

In [11]:
d = np.arange(8)

In [12]:
d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
# if we have 1d array it will append values at the end of an array.
np.append(d,100)

array([  0,   1,   2,   3,   4,   5,   6,   7, 100])

In [14]:
# if we want to append multiple values at the end of an array we have to pass list or tuple of that values.
np.append(d,[100,200])

array([  0,   1,   2,   3,   4,   5,   6,   7, 100, 200])

In [15]:
# d remains same .
d 

array([0, 1, 2, 3, 4, 5, 6, 7])

## 2d array

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# if we pass single value in 2d array ,it will convert array in 1d and append value at the end of an array.
np.append(c,100)

array([  1,   2,   3,   4,   5,   6, 100])

In [18]:
np.append(c,[[100,200,300]],axis = 0) # if we want to append row then use axis = 0

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [19]:
np.append(c,[[100],[200]], axis = 1) # if we want to append coloumn then use axis = 1

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200]])

In [20]:
c

array([[1, 2, 3],
       [4, 5, 6]])

# insert()
### syntax :- np.insert(arr, index, values, axis=None)
### def :- Insert values along the given axis before the given indices.

In [21]:
# if we do not provide axis parameter it will convert array in 1d and  insert values at specified index. 
# if we provide single value.
np.insert(c,0,100)

array([100,   1,   2,   3,   4,   5,   6])

In [22]:
np.insert(c,0,(100,200)) # we can provide tuple

array([100, 200,   1,   2,   3,   4,   5,   6])

In [23]:
np.insert(c,0,[100,200]) # also we can provide list

array([100, 200,   1,   2,   3,   4,   5,   6])

In [24]:
c # original array will not change

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.insert(c,1,100,axis = 0)

array([[  1,   2,   3],
       [100, 100, 100],
       [  4,   5,   6]])

In [26]:
np.insert(c,1,(100,200,300),axis = 0) # use tuple

array([[  1,   2,   3],
       [100, 200, 300],
       [  4,   5,   6]])

In [27]:
np.insert(c,1,[100,200,300],axis = 0) # use list

array([[  1,   2,   3],
       [100, 200, 300],
       [  4,   5,   6]])

In [28]:
np.insert(c,1,100,axis = 1) # if axis = 1 it will insert coloumn that value is 100

array([[  1, 100,   2,   3],
       [  4, 100,   5,   6]])

In [29]:
np.insert(c,1,(100,200),axis = 1) # using tuple

array([[  1, 100,   2,   3],
       [  4, 200,   5,   6]])

In [30]:
np.insert(c,1,[100,200],axis = 1) # using list

array([[  1, 100,   2,   3],
       [  4, 200,   5,   6]])

In [31]:
#Assignment: insert values 100,200,columwise at index 2 ( btwn 3 and 5)
np.insert(c,2,(100,200), axis = 1)

array([[  1,   2, 100,   3],
       [  4,   5, 200,   6]])

# delete()
### syntax :- np.delete(arr, index, axis=None)
### def :- delete values along the given axis and indices.original array will not change

In [32]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.delete(c,1) # deleted 1th index value.

array([1, 3, 4, 5, 6])

In [34]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.delete(c,1,axis = 0) # delete 1th row

array([[1, 2, 3]])

In [36]:
np.delete(c,1,axis = 1) # delete 1th coloumn

array([[1, 3],
       [4, 6]])

In [37]:
c

array([[1, 2, 3],
       [4, 5, 6]])