In [1]:
import numpy as np

### We have two similar kind of ways to convert a ndarray to 1D array : ravel() and Flatten() 
## diffrence between ravel() and flatten()
## a.ravel():
### (i) Return only reference/view of original array
### (ii) If you modify the array you would notice that the value of original array also changes.
### (iii) Ravel is faster than flatten() as it does not occupy any memory.
### (iv) Ravel is a library-level function.

## a.flatten() :
### (i) Return copy of original array
### (ii) If you modify any value of this array value of original array is not affected.
### (iii) Flatten() is comparatively slower than ravel() as it occupies memory.
### (iv) Flatten is a method of an ndarray object.


## ravel(order) 


In [2]:
a = np.array( [ (1,7,3,4),(3,2,4,1) ] )


In [3]:
a

array([[1, 7, 3, 4],
       [3, 2, 4, 1]])

In [4]:
a.ravel() # bydefault order = 'c' rowwise elements

array([1, 7, 3, 4, 3, 2, 4, 1])

In [5]:
a.ravel('f') # here order = 'f' coloumn wise elements

array([1, 3, 7, 2, 3, 4, 4, 1])

In [6]:
b = a.ravel() # create view of a

In [7]:
b

array([1, 7, 3, 4, 3, 2, 4, 1])

In [8]:
b[1] = 700 # if we make any change in b ,a will also change.

In [9]:
b

array([  1, 700,   3,   4,   3,   2,   4,   1])

In [10]:
a

array([[  1, 700,   3,   4],
       [  3,   2,   4,   1]])

## flatten(order) 

In [11]:
f = np.arange(1,21).reshape(5,4)

In [12]:
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [13]:
f.flatten() # bydefault order = 'c' row wise elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
f.flatten('f') # here order = 'f' , coloumn wise elements

array([ 1,  5,  9, 13, 17,  2,  6, 10, 14, 18,  3,  7, 11, 15, 19,  4,  8,
       12, 16, 20])

In [15]:
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [16]:
s = f.flatten() # create a copy of a

In [17]:
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
s[2] = 2000 # if we make any change in s , original array will not affected.0 

In [19]:
s

array([   1,    2, 2000,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [20]:
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

# copy()
### it returns a copy of an array.

In [21]:
c = f.copy() # create a copy of a using copy method

In [22]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [23]:
# if we make any changes in any one array , it will not affected to other.
c[0] = 1000

In [24]:
c

array([[1000, 1000, 1000, 1000],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12],
       [  13,   14,   15,   16],
       [  17,   18,   19,   20]])

In [25]:
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [26]:
b = f # create a copy of f using "=" operator. if we make any changes in one , it will affect another.


In [27]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [28]:
b[0] = 200

In [29]:
b

array([[200, 200, 200, 200],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

# view()
### it is just an view of an array.

In [30]:
f

array([[200, 200, 200, 200],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [31]:
z = f.view()

In [32]:
z

array([[200, 200, 200, 200],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [33]:
z[0] = 1 # if we make any changes in z , f will also change. 

In [34]:
z

array([[ 1,  1,  1,  1],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [35]:
f

array([[ 1,  1,  1,  1],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

# diffrence between copy() and view()
### The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

### The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

### The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.