In [1]:
import numpy as np

In [2]:
a = np.arange(1,16).reshape(5,3)

In [3]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [4]:
a.shape

(5, 3)

In [5]:
b = np.arange(1,21).reshape(5,4)

In [6]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [7]:
b.shape

(5, 4)

# reshape()
### syntax : - array_name.reshape(shape)  
### def :- create an array containing same data with new shape.it does not change original array.means original array will remain same.

In [8]:
a.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [10]:
a.shape

(5, 3)

In [11]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [12]:
np.reshape(b,(2,10))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

# resize()
### syntax : - array_name.resize(shape)  
### def :- create an array containing same data with new shape.it make inplace changes means original array will change.

In [13]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [14]:
a.shape

(5, 3)

In [15]:
a.resize(3,5)

In [16]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
a.shape

(3, 5)

In [18]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [19]:
b.resize(2,10)

In [20]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [21]:
b.shape

(2, 10)

In [22]:
b.resize(20)

In [23]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
b.resize(5,2,2)

In [25]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

### Both the numpy.reshape() and numpy.resize() methods are used to change the size of a NumPy array.
### The difference between them is that the reshape() does not changes the original array but only returns the changed array,whereas the resize() method returns nothing and directly changes the original array.